### ISSUE TITLE
Draining a WebTransport session in H2

### ISSUE THREAD

**Issue by nidhijaju** [ietf-wg-webtrans/draft-ietf-webtrans-http2#95]
For WebTransport over HTTP/3, there's a [DRAIN_WEBTRANSPORT_SESSION](https://datatracker.ietf.org/doc/html/draft-ietf-webtrans-http3#section-4.6-3) capsule for draining the session.

However, for HTTP/2, there is only a WT_STOP_SENDING capsule that would request the recipient to stop sending data, but does not require the sender of the capsule to stop sending data themselves. It would be good to have a similar concept to DRAIN_WEBTRANSPORT_SESSION for HTTP/2 to allow WebTransport to be more transport-agnostic.

**Comment by ekinnear** [comment]
Since we're trying to have WebTransport provide a common interface, regardless of underlying transport, it seems like we should be able to map each of these to a function in the overview. 

WebTransport over H2 is designed to look very similar to H3/QUIC, rather than follow H2 patterns, which should help in this area. 

Things like GOAWAY are still provided by H2 itself and are similar enough that that's probably fine. 

It should be straightforward to pull over the same DRAIN_WEBTRANSPORT_SESSION capsule from WebTransport over H3 and maintain consistency with H3.

**Comment by vasilvv** [comment]
I thought we already had similar text for using CLOSE_WEBTRANSPORT_SESSION, but I can't find it in the draft.

**Comment by DavidSchinazi** [comment]
In #98, rightfully points out that we need CLOSE_WEBTRANSPORT_SESSION in h2 to communicate the Application Error Code and Application Error Message.
